/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.ide;

import com.systemassembly.ctypes.ide.AbstractCTypesDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CTypesDslIdeModule extends AbstractCTypesDslIdeModule {
}
