/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.systemassembly.ctypes.CTypesDslRuntimeModule;
import com.systemassembly.ctypes.CTypesDslStandaloneSetup;
import com.systemassembly.ctypes.ide.CTypesDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CTypesDslIdeSetup extends CTypesDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    CTypesDslRuntimeModule _cTypesDslRuntimeModule = new CTypesDslRuntimeModule();
    CTypesDslIdeModule _cTypesDslIdeModule = new CTypesDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_cTypesDslRuntimeModule, _cTypesDslIdeModule));
  }
}
