/*
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.ui.tests;

import com.google.inject.Injector;
import com.systemassembly.ctypes.ui.internal.CtypesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CTypesDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CtypesActivator.getInstance().getInjector("com.systemassembly.ctypes.CTypesDsl");
	}

}
