/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.scoping;

import com.systemassembly.ctypes.scoping.AbstractCTypesDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CTypesDslScopeProvider extends AbstractCTypesDslScopeProvider {
}
