/*
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CTypesDslStandaloneSetup extends CTypesDslStandaloneSetupGenerated {

	def static void doSetup() {
		new CTypesDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
