/*
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CTypesDslRuntimeModule extends AbstractCTypesDslRuntimeModule {
}
