/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.ui.contentassist;

import com.systemassembly.ctypes.ui.contentassist.AbstractCTypesDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CTypesDslProposalProvider extends AbstractCTypesDslProposalProvider {
}
