/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.ui;

import com.systemassembly.ctypes.ui.AbstractCTypesDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CTypesDslUiModule extends AbstractCTypesDslUiModule {
  public CTypesDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
