/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes;

import com.systemassembly.ctypes.AbstractCTypesDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CTypesDslRuntimeModule extends AbstractCTypesDslRuntimeModule {
}
