/*
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.ide


/**
 * Use this class to register ide components.
 */
class CTypesDslIdeModule extends AbstractCTypesDslIdeModule {
}
