/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.cTypesDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslFactory
 * @model kind="package"
 * @generated
 */
public interface CTypesDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cTypesDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.systemassembly.com/ctypes/CTypesDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cTypesDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CTypesDslPackage eINSTANCE = com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.systemassembly.ctypes.cTypesDsl.impl.ModelImpl
   * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Data Type Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DATA_TYPE_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.DataTypeDefImpl <em>Data Type Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.systemassembly.ctypes.cTypesDsl.impl.DataTypeDefImpl
   * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getDataTypeDef()
   * @generated
   */
  int DATA_TYPE_DEF = 1;

  /**
   * The number of structural features of the '<em>Data Type Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_DEF_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.StructDefImpl <em>Struct Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.systemassembly.ctypes.cTypesDsl.impl.StructDefImpl
   * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getStructDef()
   * @generated
   */
  int STRUCT_DEF = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_DEF__NAME = DATA_TYPE_DEF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_DEF__FIELDS = DATA_TYPE_DEF_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Struct Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_DEF_FEATURE_COUNT = DATA_TYPE_DEF_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.StructFieldImpl <em>Struct Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.systemassembly.ctypes.cTypesDsl.impl.StructFieldImpl
   * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getStructField()
   * @generated
   */
  int STRUCT_FIELD = 3;

  /**
   * The feature id for the '<em><b>Basic Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_FIELD__BASIC_TYPE = 0;

  /**
   * The feature id for the '<em><b>Derived Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_FIELD__DERIVED_TYPE = 1;

  /**
   * The feature id for the '<em><b>Array Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_FIELD__ARRAY_SIZE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_FIELD__NAME = 3;

  /**
   * The number of structural features of the '<em>Struct Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_FIELD_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link com.systemassembly.ctypes.cTypesDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.systemassembly.ctypes.cTypesDsl.Model#getDataTypeDefinitions <em>Data Type Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data Type Definitions</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.Model#getDataTypeDefinitions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_DataTypeDefinitions();

  /**
   * Returns the meta object for class '{@link com.systemassembly.ctypes.cTypesDsl.DataTypeDef <em>Data Type Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type Def</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.DataTypeDef
   * @generated
   */
  EClass getDataTypeDef();

  /**
   * Returns the meta object for class '{@link com.systemassembly.ctypes.cTypesDsl.StructDef <em>Struct Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Struct Def</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructDef
   * @generated
   */
  EClass getStructDef();

  /**
   * Returns the meta object for the attribute '{@link com.systemassembly.ctypes.cTypesDsl.StructDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructDef#getName()
   * @see #getStructDef()
   * @generated
   */
  EAttribute getStructDef_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.systemassembly.ctypes.cTypesDsl.StructDef#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructDef#getFields()
   * @see #getStructDef()
   * @generated
   */
  EReference getStructDef_Fields();

  /**
   * Returns the meta object for class '{@link com.systemassembly.ctypes.cTypesDsl.StructField <em>Struct Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Struct Field</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructField
   * @generated
   */
  EClass getStructField();

  /**
   * Returns the meta object for the attribute '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getBasicType <em>Basic Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Basic Type</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructField#getBasicType()
   * @see #getStructField()
   * @generated
   */
  EAttribute getStructField_BasicType();

  /**
   * Returns the meta object for the reference '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getDerivedType <em>Derived Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Derived Type</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructField#getDerivedType()
   * @see #getStructField()
   * @generated
   */
  EReference getStructField_DerivedType();

  /**
   * Returns the meta object for the attribute '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getArraySize <em>Array Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array Size</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructField#getArraySize()
   * @see #getStructField()
   * @generated
   */
  EAttribute getStructField_ArraySize();

  /**
   * Returns the meta object for the attribute '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.systemassembly.ctypes.cTypesDsl.StructField#getName()
   * @see #getStructField()
   * @generated
   */
  EAttribute getStructField_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CTypesDslFactory getCTypesDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.systemassembly.ctypes.cTypesDsl.impl.ModelImpl
     * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Data Type Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DATA_TYPE_DEFINITIONS = eINSTANCE.getModel_DataTypeDefinitions();

    /**
     * The meta object literal for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.DataTypeDefImpl <em>Data Type Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.systemassembly.ctypes.cTypesDsl.impl.DataTypeDefImpl
     * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getDataTypeDef()
     * @generated
     */
    EClass DATA_TYPE_DEF = eINSTANCE.getDataTypeDef();

    /**
     * The meta object literal for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.StructDefImpl <em>Struct Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.systemassembly.ctypes.cTypesDsl.impl.StructDefImpl
     * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getStructDef()
     * @generated
     */
    EClass STRUCT_DEF = eINSTANCE.getStructDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRUCT_DEF__NAME = eINSTANCE.getStructDef_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRUCT_DEF__FIELDS = eINSTANCE.getStructDef_Fields();

    /**
     * The meta object literal for the '{@link com.systemassembly.ctypes.cTypesDsl.impl.StructFieldImpl <em>Struct Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.systemassembly.ctypes.cTypesDsl.impl.StructFieldImpl
     * @see com.systemassembly.ctypes.cTypesDsl.impl.CTypesDslPackageImpl#getStructField()
     * @generated
     */
    EClass STRUCT_FIELD = eINSTANCE.getStructField();

    /**
     * The meta object literal for the '<em><b>Basic Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRUCT_FIELD__BASIC_TYPE = eINSTANCE.getStructField_BasicType();

    /**
     * The meta object literal for the '<em><b>Derived Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRUCT_FIELD__DERIVED_TYPE = eINSTANCE.getStructField_DerivedType();

    /**
     * The meta object literal for the '<em><b>Array Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRUCT_FIELD__ARRAY_SIZE = eINSTANCE.getStructField_ArraySize();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRUCT_FIELD__NAME = eINSTANCE.getStructField_Name();

  }

} //CTypesDslPackage
