/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.cTypesDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type Def</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getDataTypeDef()
 * @model
 * @generated
 */
public interface DataTypeDef extends EObject
{
} // DataTypeDef
