/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.cTypesDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.systemassembly.ctypes.cTypesDsl.StructDef#getName <em>Name</em>}</li>
 *   <li>{@link com.systemassembly.ctypes.cTypesDsl.StructDef#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructDef()
 * @model
 * @generated
 */
public interface StructDef extends DataTypeDef
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.systemassembly.ctypes.cTypesDsl.StructDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link com.systemassembly.ctypes.cTypesDsl.StructField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructDef_Fields()
   * @model containment="true"
   * @generated
   */
  EList<StructField> getFields();

} // StructDef
