/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.cTypesDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.systemassembly.ctypes.cTypesDsl.StructField#getBasicType <em>Basic Type</em>}</li>
 *   <li>{@link com.systemassembly.ctypes.cTypesDsl.StructField#getDerivedType <em>Derived Type</em>}</li>
 *   <li>{@link com.systemassembly.ctypes.cTypesDsl.StructField#getArraySize <em>Array Size</em>}</li>
 *   <li>{@link com.systemassembly.ctypes.cTypesDsl.StructField#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructField()
 * @model
 * @generated
 */
public interface StructField extends EObject
{
  /**
   * Returns the value of the '<em><b>Basic Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basic Type</em>' attribute.
   * @see #setBasicType(String)
   * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructField_BasicType()
   * @model
   * @generated
   */
  String getBasicType();

  /**
   * Sets the value of the '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getBasicType <em>Basic Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basic Type</em>' attribute.
   * @see #getBasicType()
   * @generated
   */
  void setBasicType(String value);

  /**
   * Returns the value of the '<em><b>Derived Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derived Type</em>' reference.
   * @see #setDerivedType(DataTypeDef)
   * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructField_DerivedType()
   * @model
   * @generated
   */
  DataTypeDef getDerivedType();

  /**
   * Sets the value of the '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getDerivedType <em>Derived Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Derived Type</em>' reference.
   * @see #getDerivedType()
   * @generated
   */
  void setDerivedType(DataTypeDef value);

  /**
   * Returns the value of the '<em><b>Array Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Size</em>' attribute.
   * @see #setArraySize(int)
   * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructField_ArraySize()
   * @model
   * @generated
   */
  int getArraySize();

  /**
   * Sets the value of the '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getArraySize <em>Array Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array Size</em>' attribute.
   * @see #getArraySize()
   * @generated
   */
  void setArraySize(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.systemassembly.ctypes.cTypesDsl.CTypesDslPackage#getStructField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.systemassembly.ctypes.cTypesDsl.StructField#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // StructField
