/**
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.cTypesDsl.impl;

import com.systemassembly.ctypes.cTypesDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CTypesDslFactoryImpl extends EFactoryImpl implements CTypesDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CTypesDslFactory init()
  {
    try
    {
      CTypesDslFactory theCTypesDslFactory = (CTypesDslFactory)EPackage.Registry.INSTANCE.getEFactory(CTypesDslPackage.eNS_URI);
      if (theCTypesDslFactory != null)
      {
        return theCTypesDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CTypesDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CTypesDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CTypesDslPackage.MODEL: return createModel();
      case CTypesDslPackage.DATA_TYPE_DEF: return createDataTypeDef();
      case CTypesDslPackage.STRUCT_DEF: return createStructDef();
      case CTypesDslPackage.STRUCT_FIELD: return createStructField();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataTypeDef createDataTypeDef()
  {
    DataTypeDefImpl dataTypeDef = new DataTypeDefImpl();
    return dataTypeDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StructDef createStructDef()
  {
    StructDefImpl structDef = new StructDefImpl();
    return structDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StructField createStructField()
  {
    StructFieldImpl structField = new StructFieldImpl();
    return structField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CTypesDslPackage getCTypesDslPackage()
  {
    return (CTypesDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CTypesDslPackage getPackage()
  {
    return CTypesDslPackage.eINSTANCE;
  }

} //CTypesDslFactoryImpl
