/*
 * generated by Xtext 2.18.0.M3
 */
package com.systemassembly.ctypes.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCTypesDslScopeProvider extends DelegatingScopeProvider {
}
